spectatorpublishing/Clubs-2020

README.md
src/App.js
src/components/faqbox/index.js
src/components/navbar/index.js
src/theme.js

Uses the ThemeProvider component from styled-components to creating a theme system to ensure that only the colors specified in the figma file are being used. 
I also added an example of how to use a theme provider in the readme for those who have never used one. It has to be used with a styled component.

Update color foundation

---

src/components/faqbox/index.js
src/containers/FAQ.js

Added all faq boxes and background color.
Changed margin size of faq boxes. 
Pending: Updates on how to implement the special styling for the background/navbar

Updated General Styling of FAQ Page

---

src/containers/FAQ.js
src/theme.js

- Added background color to theme 
- Changed the background color to light gray from the theme

Added color to theme

---

package-lock.json
package.json
src/App.js
src/components/checkbox/index.js
src/components/dropdown/index.js
src/components/navbar/index.js
src/components/searchTag/index.js
src/containers/ProfileCreation.js
src/index.css

Adds the 3 components mentioned above. They can be seen at the /profile-creation route. The components are accessible. There are no readability issues, and the dropdown menu can be controlled with arrow keys and the enter button.
This is how they look:

Searchtag checkbox dropdown

---

client/src/App.js
client/src/components/profilePageBox/index.js
client/src/containers/ProfileBoxTester.js

I added the Profile Page Box component. I used functions since some of the props were arrays and booleans, but open to changing the format. I also included a tester --> "ProfileBoxTester" that can be deleted after. I just found it helpful while working to see what the changes looked like.

Profile page box

---

server/controllers/clubProfileController.js

This PR adds the more specific querying functionality to the clubProfileControllers.
Changes:
1. Implemented getAll function in clubProfileControllers.js to only select and return the fields displayed in the club overview cards (on the front page) using the Figma mockup as a guide
2. Required database from ../models/index.js

getAll function return only selected fields

---

client/src/components/frequencyTag/index.js
client/src/containers/ProfileBoxTester.js

Created meeting frequency component and tested it in ProfileBoxTester

Meeting frequency component

---

client/src/components/explorebox/index.js
client/src/components/filters/join.js
client/src/components/filters/shuffle.js
client/src/components/filters/size.js
client/src/components/filters/type.js
client/src/containers/Explore.js

Implemented explore boxes to load data dynamically from fetch request, made the cards responsive and styled the filter buttons.

Explore main page

---

server/controllers/clubAccountControllers.js
server/models/ClubAccountModel.js
server/routes/clubAccountRoutes.js
server/server.js

This PR creates a basic DB schema design for the data structure that we'll be storing user account information in, as well as configures the routes for specific endpoints related to this object
1. Created db schema in `server/models/ClubAccountModel.js`.
2. Created template code for all the functions/controllers related to this schema in `server/controllers/clubAccountControllers.js`.
3. Created the frontend endpoints corresponding to the controllers in `server/routes/clubAccountRoutes.js`.
4. Added the endpoints to the server in `server/server.js`.
@TannerTreasure @adibsad @ic372 @zhuci 
@CarolineHoang @erin2722 @Paul2858 @mckennagillard

[Database] Club account model & endpoints

---

server/config/index.js
server/controllers/clubAccountControllers.js

Implemented clubAccountControllers for getProfile, getByID, getByFirebaseId, and getAll. Specifically, getAll returns all pending club account sorted by oldest request first, followed by all nonpending club accounts that have been updated within the last 14 days, sorted by the oldest update first.

Club account controllers T

---

server/controllers/clubAccountControllers.js
server/controllers/clubProfileController.js
server/routes/clubAccountRoutes.js

This PR implements the `create`, `delete` and `changeVerificationStatus` functions for the `clubAccount` model.

Club account create controller

---

client/src/App.js
client/src/components/accountTag/index.js
client/src/containers/AccountTagTest.js

Created skeleton for account tag

Created Account Tag

---

server/models/ClubProfileModel.js

Added an extra `String` field in the club profile db schema for the link to the mailing list of the club.
See file `server/models/ClubProfileModel.js`.

[Database] Added mailing list link in club profile model

---

package-lock.json
package.json
public/index.html
src/App.js
src/components/clubprofile/changeEmail.js
src/components/clubprofile/changePassword.js
src/components/clubprofile/confirmation.js
src/components/clubprofile/index.js
src/components/clubprofile/input.js
src/components/clubprofile/manageAccount.js
src/components/clubprofile/updateAccountInfo.js
src/components/navbar/index.js
src/components/signup/index.js
src/containers/ClubProfile.js
src/containers/Confirmation.js
src/containers/SignUp.js
src/firebase.js
src/test/firebase/sendEmail.jsx
src/test/firebase/signin.jsx
src/test/firebase/signup.jsx
src/test/signup/checkPassword.js
src/test/signup/password.jsx

#76 
- Complete the front-end of pop-up for updating club account email and passwords. 
- still need to fill in the back-end APIs to update passwords and fetch club info when these are implemented
Here's how this component looks now:
--------
#33 
Add test component for testing firebase auth's email verification features. To test, simply add a route in App.js by importing the `<SendEmail/>` component from 'src/test/firebase/sendEmail.jsx' relative to the project root.
- Once successfully signed into google, the page will display a welcome message or an error message otherwise
- An verification/Welcome email will be sent to the gmail of the google account you signed in upon successful login. If the email is sent successfully, a success message will appear. Otherwise, the error will be …

Firebase auth

---

src/App.js
src/components/navbar/index.js
src/components/signup/index.js
src/containers/Confirmation.js
src/containers/SignUp.js

#35 
- Component/template for sign up, confirmation, and sign in 
- Container for sign up, and sign in
Browser: 
iPhone X:

sign up and confirmation containers. can also be used for sign in.

---

server/common/index.js
server/controllers/clubAccountControllers.js
server/controllers/clubProfileController.js

Miscellaneous modifications to make club account/profile controllers more robust for edge cases.
1. Added more descriptive error-handling that returns to frontend the error type and message.
2. For `clubAccountControllers.create`, check if the object already exists before creating to ensure uniqueness of firebaseId.
3. Miscellaneous changes to ensure data format integrity (i.e. default value for `clubAccount.deniedReason` is '' not `null`, and `getProfile` / `getByFirebaseId` should return `null` instead of an empty array in the case where the object is not found.

[Database] Club account/profile controllers fixes

---

client/src/components/completeProfile/index.js
client/src/components/filters/filterMobile.js
client/src/components/filters/join.js
client/src/components/filters/type.js
client/src/components/searchTag/index.js
client/src/components/searchTagActive/index.js
client/src/containers/ClubProfile.js
client/src/containers/Explore.js
client/src/containers/ProfileCreation/ProfileCreation.js
client/src/containers/ProfileCreation/ProfileCreation1/helpers.js

- searchTag and searchTagActive components
- fixed filter button colors on explore page
- created reminder banner for completing profile

active and inactive toggling for club tags

---

client/src/components/navbarProfile/index.js
client/src/containers/ClubProfile.js

- Removed links from Club Admin specific navbar
- Added temporary button to toggle admin/user view
- Updated Club Profile code to condense components

Minor Frontend Updates

---

client/src/components/adCarrier/index.js
client/src/components/filters/join.js
client/src/components/filters/size.js
client/src/components/filters/type.js
client/src/containers/Explore.js

Implements mobile responsive versions of the 3 dropdowns for the filtering criteria, it is not yet connected to the backend.

Filter Dropdowns On Explore page

---

server/controllers/clubProfileController.js
server/routes/clubProfileRoutes.js

- Wrote the search function 
- returns a json object that contains properties 'name', 'shortDescription', 'longDescription'
- these properties contain the search of club profiles names, shortDescription, and long description
- WARNING: contains duplicates

Search function

---

client/src/App.js
client/src/components/signout/index.js
client/src/components/signup/helper.js
client/src/components/signup/index.js
client/src/components/tomatoButton/index.js
client/src/containers/FirebaseApiSetUpTest/firebase/signin.jsx
client/src/containers/Login.js
client/src/containers/SignUp.js

Implemented Login/Logout & Signup Functionality For Login Modal

---

client/src/App.js
client/src/components/filters/join.js
client/src/components/filters/size.js
client/src/components/filters/type.js
client/src/components/searchBar/index.js
client/src/containers/ClubProfile.js
client/src/containers/Explore.js
client/src/containers/FAQ.js
package.json

- Fixed bug with background waves for Club Profile Page and FAQ Page
- (Kind of) fixed mobile/desktop responsiveness for Explore Page Ads (Explore page was showing desktop Ads for all window sizes):
1. ISSUE ❗: Window event listener works, but the page does not re-render with the change of width so Ad does not dynamically change with the width change.
2. ISSUE❗ I'm seeing an issue with the search bar, I can only type one letter and the bar clears when I type another letter. Not sure why that is happening, I didn't change anything about the search bar on my end.
3. General Comment: AdCarrier does not render properly if I use conditional render component so I had to do two separate page renders (one for mobile/ one for desktop) in order for the Ads to render. To avoid too much code …

Frontend updates

---

server/controllers/clubProfileController.js
server/models/ClubAccountModel.js
server/models/ClubProfileModel.js
server/routes/clubProfileRoutes.js

Refer to issue #125 for more information!

[Databases] Updated club profile models and related functions

---

client/src/components/navbar/index.js
client/src/components/navbarProfile/index.js

- My Profile and FAQs buttons added to navbar when logged in
- My Profile button link currently redirects to explore page

navbar update for login

---

client/src/components/socialTagsBox/index.js
client/src/containers/ClubProfile.js

Fixed social media link hardcoding. Email name will appear blank in the sidebar for a club profile until a value is stored (it should display the actual address when active).

Social links fix

---

server/controllers/clubProfileController.js
server/models/ClubProfileModel.js

GetAll now only returns clubs associated with approved accounts and who have completed there profiles

Updated club Profile model with a status attribute and updated GetAll 

---

client/src/App.js
client/src/components/ListOfClubs/wrapper.js
client/src/components/navbar/index.js
client/src/containers/ClubProfileDisplay.js
client/src/containers/Explore.js
client/src/containers/FAQ.js
client/src/containers/ProfileCreation/ProfileCreationMaster.js

- lifted the navbar to be global
- added logic to alter what buttons are available to the user depending on whether they are logged in or not
- resolved additional bugs

Global nav

---

client/src/components/clubprofile/confirmation.js
client/src/components/filters/type.js
client/src/components/signup/index.js
client/src/containers/ClubAccountManagement.js
client/src/containers/Explore.js
client/src/containers/FAQ.js
client/src/containers/Portal.js

Mobile: Make filter buttons row, not column; Fix spacing for shuffle button
General: Make admin portal buttons actual styled buttons

Squashin Bugs (Matthew)

---

client/src/components/tomatoButton/index.js
client/src/containers/ClubProfileDisplay.js
client/src/containers/Explore.js

- club cards arranged in 2 columns on explore page
- changed text alignment on club profile pages
- changed font size on register club button

club cards alignment & other tweaks
